name = "portfolio-hafiz-worker"
type = "webpack"
compatibility_date = "2024-04-15"

[site]
bucket = "dist"
entry-point = "worker.js"
pages = "dist"
pages_build_output_dir = "dist"

[env.production]
zone_id = "4591312ec6e7e5e63395b5dbf321fcd5"
route = "hafizza.com/*"